config/routes.rb
Rails.application.routes.draw do
  resources :features
  
  root "chairs#index"

  resources :chairs do 
    resources :favorites, only: [:create, :destroy]
    resources :reviews
  end

  resource :session, only: [:new, :create, :destroy] #note resource and session is singular

  resources :users
  get "signup" => "users#new"
  get "chairs/filter/:filter" => "chairs#index", as: :filtered_chairs

end

app/models/chair.rb
class Chair < ApplicationRecord

  before_save :set_slug
  before_validation :set_slug, on: [:create]


  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :likers, through: :favorites, source: :user
  has_many :feature_assignments, dependent: :destroy
  has_many :features, through: :feature_assignments
  belongs_to :user

  has_one_attached :main_image

  validate :acceptable_image
  validates :name, :available_from, :user, presence: true
  validates :slug, presence: true, uniqueness: true


  scope :available, -> { where("available_from < ?", Time.now).order("available_from") }
  # TODO: change Time.now to Time.current
  scope :low_price_chair, -> { where("price < ?", 500).order("price") }

  def average_rating
    return nil if reviews.none?
    
    reviews.average(:stars).round.to_i
  end

  def to_param 
    slug
  end 

  private 

  def set_slug
    self.slug = name.parameterize
  end 

  def acceptable_image
    return unless main_image.attached?

    unless main_image.blob.byte_size <= 1.megabyte
      errors.add(:main_image, "is too big")
    end
  
    acceptable_types = ["image/jpeg", "image/jpg", "image/png"]
    unless acceptable_types.include?(main_image.blob.content_type)
      errors.add(:main_image, "must be a JPG, JPEG or PNG")
    end
  end 
end

app/controllers/chairs_controller.rb
class ChairsController < ApplicationController

  before_action :require_admin_or_verified, only: [:new, :create]
  before_action :set_chair, only: [:show, :edit, :update, :destroy]

  def index 
    # TODO: Don't use case statements in Rails
    @chairs = { 
      "available" => Chair.available, 
      "low_price_chair" => Chair.low_price_chair
    }[params[:filter]] || Chair.all
  end

  def show 
    @features = @chair.features.order(:name)
    @likers = @chair.likers 
  end

  def edit 
    
  end 

  def update
    if @chair.update(chair_params)
      flash[:notice] = "Chair successfully updated!"
      redirect_to @chair
    else  
      render :edit, status: :unprocessable_entity
    end
  end 

  def new
    @chair = Chair.new 
  end
  
  def create 
    @chair = current_user.chairs.build(chair_params) 
    if @chair.save
      flash[:notice] = "Chair successfully created!"
      redirect_to @chair
    else  
      render :new, status: :unprocessable_entity #renders :new form with all valid form data
    end
  end

  def destroy
    @chair.destroy 
    
    flash[:notice] = "Chair successfully destroyed" 
    redirect_to root_path, status: :see_other
  end

  private

  def chair_params
    params.require(:chair).permit(:name, :price, :company, :main_image, :description, :available_from, :feature_ids => [])
  end

  def set_chair
    @chair = Chair.find_by!(slug: params[:id])
  end
end

app/helpers/chairs_helper.rb
module ChairsHelper

  def isPast?(datetime)
    datetime < Time.now
  end 

  def display_availability(chair)
    if chair.available_from.nil?
        "Availability not specified"
    elsif (isPast?(chair.available_from))
        "Available Now!"
    else  
        "Available from #{chair.available_from.strftime('%Y-%m-%d')}"
    end
  end 

  def label_classes 
    # py-2 not tailwind
    "block text-sm font-medium leading-6 text-gray-900 py-2"
  end 

  def form_field_classes
    "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
  end

  def form_input_classes 
    "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
  end

  def form_field_with_error_classes
    "mt-2 text-sm text-red-600"
  end

  def form_field_button_classes
    "rounded-md bg-indigo-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 mt-2" 
  end

  def main_image(chair)
    if chair.main_image.attached?
      image_tag chair.main_image
        #.variant(resize_to_limit: [300, 300])
    else
      image_tag "placeholder_chair.jpg"
    end
  end

  def nav_link_url(scope)
    current_page?(filtered_chairs_path(scope)) ? chairs_url : filtered_chairs_path(scope)
  end
  

  def user_likes_chair?(user, chair)
    user && chair.likers.exists?(id: user.id)
  end 

end

app/views/chairs/_card.html.erb
<!--
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/aspect-ratio'),
    ],
  }
  ```
-->
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 sm:px-6 lg:max-w-7xl lg:px-8"> <!-- removed sm:py-24 and py-16 to fix padding on desktop -->
    <h2 class="sr-only">Products</h2>

    <div class="grid grid-cols-1 gap-y-4 sm:grid-cols-2 sm:gap-x-6 sm:gap-y-10 lg:grid-cols-3 lg:gap-x-8">
    <% chair.each do |chair| %>
      <div class="group relative flex flex-col overflow-hidden rounded-lg border border-gray-200 bg-white">
        <div class="aspect-h-4 aspect-w-3 bg-gray-200 sm:aspect-none group-hover:opacity-75 sm:h-96">
          <%= main_image(chair) %>
          <%# <img src="https://tailwindui.com/img/ecommerce-images/category-page-02-image-card-01.jpg" alt="Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green." class="h-full w-full object-cover object-center sm:h-full sm:w-full"> %>
          <%# if chair.picture.present? %>
						<%#= image_tag chair.picture, class: "h-full w-full object-cover object-center sm:h-full sm:w-full"%>
          <%# else %>
            <%#= image_tag "placeholder_chair.jpg", class: "h-full w-full object-cover object-center sm:h-full sm:w-full"%>
          <%# end %>
        </div>
        <div class="flex flex-1 flex-col space-y-2 p-4">
          <h3 class="text-sm font-medium text-gray-900">
            <%= link_to "", chair, class: "absolute inset-0", aria: {hidden: true} %>
              <span><%= chair.name %></span>
              
          </h3>
          <p class="text-sm text-gray-500"><%= truncate(chair.description) %></p>
          <div class="flex flex-1 flex-col justify-end">
            <p class="text-sm italic text-gray-500"><%= chair.company %></p>
            <p class="text-base font-medium text-gray-900">$<%= chair.price %></p>
            <p class="text-base font-medium text-gray-900"> <%= display_availability(chair) %></p>
          </div>
        </div>
      </div>
    <% end %>
    <!-- End of card -->
      <%# <div class="group relative flex flex-col overflow-hidden rounded-lg border border-gray-200 bg-white">
        <div class="aspect-h-4 aspect-w-3 bg-gray-200 sm:aspect-none group-hover:opacity-75 sm:h-96">
          <img src="https://tailwindui.com/img/ecommerce-images/category-page-02-image-card-02.jpg" alt="Front of plain black t-shirt." class="h-full w-full object-cover object-center sm:h-full sm:w-full">
        </div>
        <div class="flex flex-1 flex-col space-y-2 p-4">
          <h3 class="text-sm font-medium text-gray-900">
            <a href="#">
              <span aria-hidden="true" class="absolute inset-0"></span>
              Basic Tee
            </a>
          </h3>
          <p class="text-sm text-gray-500">Look like a visionary CEO and wear the same black t-shirt every day.</p>
          <div class="flex flex-1 flex-col justify-end">
            <p class="text-sm italic text-gray-500">Black</p>
            <p class="text-base font-medium text-gray-900">$32</p>
          </div>
        </div>
      </div> %>

      <!-- More products... -->
    </div>
  </div>
</div>

app/views/chairs/_form.html.erb
<div class="container mx-auto px-4 mt-8 max-w-xs py-16">
  <%= simple_form_for chair, defaults: {label_html: {class: label_classes}, input_html: {class: form_input_classes}} do |f| %>

    <% if f.object.errors.present? %>
      <%= render "shared/errors", errors: f.object.errors %>
    <% end %>

    <%= f.input :name, error: false %>
    <%= f.full_error :name, class: form_field_with_error_classes %>
    <%= f.input :price %>
    <%= f.input :company %>
    <%= f.input :main_image %>
    <%= f.input :description %>
    <%= f.input :available_from, error: false, include_blank: true %>
    <%= f.full_error :available_from,  class: form_field_with_error_classes %>

    <fieldset>
      <legend class="sr-only">Features</legend>
      <div class="space-y-5">
        <%= f.association :features, 
                          as: :check_boxes, 
                          wrapper: false, 
                          item_wrapper_tag: :div, 
                          item_wrapper_class: 'relative flex items-center space-x-3 space-y-5', 
                          label_html: { class: 'text-sm leading-6 font-medium text-gray-900' }, 
                          input_html: { class: 'h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600' } %>
      </div>
    </fieldset>

    <%= f.button :submit, class: form_field_button_classes %>
  <% end %>
</div>

app/views/chairs/_heart.html.erb
<% if current_user && current_user.liked_chairs.include?(@chair) %>
<svg class="h-6 w-6 flex-shrink-0" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
  <path d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" fill="red" />
</svg>
  <span class="sr-only">Remove from favorites</span>
<% else %>
  <svg class="h-6 w-6 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
  </svg>
  <span class="sr-only">Add to favorites</span>
<% end %>

app/views/chairs/_product_overview.html.erb
<!--
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/typography'),
      require('@tailwindcss/aspect-ratio'),
    ],
  }
  ```
-->
<div class="bg-white mt-2"> <!-- added mt-2 to fix padding -->
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <div class="lg:grid lg:grid-cols-2 lg:items-start lg:gap-x-8">
      <!-- Image gallery -->
      <div class="flex flex-col-reverse">
        <!-- Image selector -->
        <div class="mx-auto mt-6 hidden w-full max-w-2xl sm:block lg:max-w-none">
          <div class="grid grid-cols-4 gap-6" aria-orientation="horizontal" role="tablist">
            <button id="tabs-1-tab-1" class="relative flex h-24 cursor-pointer items-center justify-center rounded-md bg-white text-sm font-medium uppercase text-gray-900 hover:bg-gray-50 focus:outline-none focus:ring focus:ring-opacity-50 focus:ring-offset-4" aria-controls="tabs-1-panel-1" role="tab" type="button">
              <span class="sr-only">Angled view</span>
              <span class="absolute inset-0 overflow-hidden rounded-md">
                            <%# if @chair.picture.present? %>
                              <%#= image_tag @chair.picture, class: "h-full w-full object-cover object-center"%>
                              <%# else %>
                                <%#= image_tag "placeholder_chair.jpg", class: "h-full w-full object-cover object-center sm:h-full sm:w-full"%>
                            <%# end %>
                <%# <img src="https://tailwindui.com/img/ecommerce-images/product-page-03-product-01.jpg" alt="" class="h-full w-full object-cover object-center"> %>
              </span>
              <!-- Selected: "ring-indigo-500", Not Selected: "ring-transparent" -->
              <span class="ring-transparent pointer-events-none absolute inset-0 rounded-md ring-2 ring-offset-2" aria-hidden="true"></span>
            </button>

            <!-- More images... -->
          </div>
        </div>

        <div class="aspect-h-1 aspect-w-1 w-full">
          <!-- Tab panel, show/hide based on tab state. -->
          <div id="tabs-1-panel-1" aria-labelledby="tabs-1-tab-1" role="tabpanel" tabindex="0">
          <%= main_image(@chair) %>
                        <%# if @chair.picture.present? %>
  <%#= image_tag @chair.picture, class: "h-full w-full object-cover object-center sm:rounded-lg"%>
<%# end %>
            <%# <img src="https://tailwindui.com/img/ecommerce-images/product-page-03-product-01.jpg" alt="Angled front view with bag zipped and handles upright." class="h-full w-full object-cover object-center sm:rounded-lg"> %>
          </div>

          <!-- More images... -->
        </div>
      </div>

      <!-- Product info -->
      <div class="mt-10 px-4 sm:mt-16 sm:px-0 lg:mt-0">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900"><%= @chair.company %> <%= @chair.name %></h1>

        <div class="mt-3">
          <h2 class="sr-only">Product information</h2>
          <p class="text-3xl tracking-tight text-gray-900">$<%= @chair.price %></p>
        </div>

        <!-- Reviews -->
        <div class="mt-3">
          <h3 class="sr-only">Reviews</h3>
          <div class="flex items-center">
            <div class="flex items-center">
              <!-- Active: "text-indigo-500", Inactive: "text-gray-300" -->
              <svg class="h-5 w-5 flex-shrink-0 text-indigo-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
              </svg>
              <svg class="h-5 w-5 flex-shrink-0 text-indigo-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
              </svg>
              <svg class="h-5 w-5 flex-shrink-0 text-indigo-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
              </svg>
              <svg class="h-5 w-5 flex-shrink-0 text-indigo-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
              </svg>
              <svg class="h-5 w-5 flex-shrink-0 text-gray-300" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
              </svg>
            </div>
            <div class="ml-4 flex">
              <%= link_to "See all #{@chair.reviews.size} reviews", chair_reviews_path(@chair), class: "text-sm font-medium text-indigo-600 hover:text-indigo-500" %>
 
            </div>
            <p class="sr-only">4 out of 5 stars</p>
          </div>
        </div>

        <div class="mt-6">
          <h3 class="sr-only">Description</h3>

          <div class="space-y-6 text-base text-gray-700">
            <p><%= @chair.description %></p>
          </div>
        </div>

        <form class="mt-6">
          <!-- Colors -->
          <div>
            <h3 class="text-sm text-gray-600">Color</h3>

            <fieldset class="mt-2">
              <legend class="sr-only">Choose a color</legend>
              <span class="flex items-center space-x-3">
                <!--
                  Active and Checked: "ring ring-offset-1"
                  Not Active and Checked: "ring-2"
                -->
                <label class="relative -m-0.5 flex cursor-pointer items-center justify-center rounded-full p-0.5 focus:outline-none ring-gray-700">
                  <input type="radio" name="color-choice" value="Washed Black" class="sr-only" aria-labelledby="color-choice-0-label">
                  <span id="color-choice-0-label" class="sr-only">Washed Black</span>
                  <span aria-hidden="true" class="h-8 w-8 bg-gray-700 rounded-full border border-black border-opacity-10"></span>
                </label>
                <!--
                  Active and Checked: "ring ring-offset-1"
                  Not Active and Checked: "ring-2"
                -->
                <label class="relative -m-0.5 flex cursor-pointer items-center justify-center rounded-full p-0.5 focus:outline-none ring-gray-400">
                  <input type="radio" name="color-choice" value="White" class="sr-only" aria-labelledby="color-choice-1-label">
                  <span id="color-choice-1-label" class="sr-only">White</span>
                  <span aria-hidden="true" class="h-8 w-8 bg-white rounded-full border border-black border-opacity-10"></span>
                </label>
                <!--
                  Active and Checked: "ring ring-offset-1"
                  Not Active and Checked: "ring-2"
                -->
                <label class="relative -m-0.5 flex cursor-pointer items-center justify-center rounded-full p-0.5 focus:outline-none ring-gray-500">
                  <input type="radio" name="color-choice" value="Washed Gray" class="sr-only" aria-labelledby="color-choice-2-label">
                  <span id="color-choice-2-label" class="sr-only">Washed Gray</span>
                  <span aria-hidden="true" class="h-8 w-8 bg-gray-500 rounded-full border border-black border-opacity-10"></span>
                </label>
              </span>
            </fieldset>
          </div>

          <div class="mt-10 flex">
            <button type="submit" class="flex max-w-xs flex-1 items-center justify-center rounded-md border border-transparent bg-indigo-600 px-8 py-3 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-50 sm:w-full">Add to bag</button>


        </form>


        <% if user_likes_chair?(current_user, @chair) %>
          <!-- Liked state -->
          <%= button_to chair_favorite_path(@chair), method: :delete, class: "ml-4 flex items-center justify-center rounded-md px-3 py-3 text-gray-400 hover:bg-gray-100 hover:text-gray-500" do %>
          <%= render "heart" %>
          <% end %>
        <% else %>
          <!-- Unliked state -->
          <%= button_to chair_favorites_path(@chair), class: "ml-4 flex items-center justify-center rounded-md px-3 py-3 text-gray-400 hover:bg-gray-100 hover:text-gray-500" do %>
          <%= render "heart" %>
          <% end %>
        <% end %> 




         
          </div>
        <section aria-labelledby="details-heading" class="mt-12">
          <h2 id="details-heading" class="sr-only">Additional details</h2>

          <div class="divide-y divide-gray-200 border-t">
            <div>
              <h3>
                <!-- Expand/collapse question button -->
                <button type="button" class="group relative flex w-full items-center justify-between py-6 text-left" aria-controls="disclosure-1" aria-expanded="false">
                  <!-- Open: "text-indigo-600", Closed: "text-gray-900" -->
                  <span class="text-gray-900 text-sm font-medium">Features</span>
                  <span class="ml-6 flex items-center">
                    <!-- Open: "hidden", Closed: "block" -->
                    <svg class="block h-6 w-6 text-gray-400 group-hover:text-gray-500" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                    </svg>
                    <!-- Open: "block", Closed: "hidden" -->
                    <svg class="hidden h-6 w-6 text-indigo-400 group-hover:text-indigo-500" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15" />
                    </svg>
                  </span>
                </button>
              </h3>
              <div class="prose prose-sm pb-6" id="disclosure-1">
                <ul role="list">
                  <% @features.each do |f| %>
                    <li><%= f.name %></li>
                  <% end %>
                </ul>
              </div>
            </div>

            <!-- More sections... -->
          </div>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/chairs/edit.html.erb
<h1>Edit Chair</h1>

<%= render "form", chair: @chair %>

app/views/chairs/index.html.erb
<%= render "category_filter" %>

<% if current_user_admin?  || current_user_verified? %>
<div class="flex justify-center py-16">
  <button type="button" class="rounded-md bg-indigo-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
    <%= link_to "New Chair", new_chair_path %>
  </button>
</div>
<% end %>

app/views/chairs/new.html.erb
<h1>New Chair</h1>
<%= render "form", chair: @chair %>

app/views/chairs/show.html.erb
<%= render "product_overview" %>

<% if current_user_admin? || current_user_owner?(@chair) %>
<div class="flex justify-center py-16 gap-4">
  <button type="button" class="rounded-md bg-indigo-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
    <%= link_to "Edit Chair", edit_chair_path %>
  </button>
  <button type="button" class="rounded-md bg-indigo-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
    <%= link_to "Delete Chair", @chair, 
      data: { turbo_method: :delete, turbo_confirm: "Really?" } %>
  </button>
</div>
<% end %>