config/routes.rb
Rails.application.routes.draw do
  resources :features
  
  root "chairs#index"

  resources :chairs do 
    resources :favorites, only: [:create, :destroy]
    resources :reviews
  end

  resource :session, only: [:new, :create, :destroy] #note resource and session is singular

  resources :users
  get "signup" => "users#new"
  get "chairs/filter/:filter" => "chairs#index", as: :filtered_chairs

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :require_signin, except: [:index]
  before_action :set_chair

  def index 
    @reviews = @chair.reviews.all
  end

  def new
    @review = @chair.reviews.new 
  end

  def create 
    @review = @chair.reviews.new(review_params)
    @review.user = current_user
    if @review.save 
      redirect_to chair_reviews_path(@chair), notice: "Review created successfully"
    else  
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @review = @chair.reviews.find(params[:id])
  end

  def update 
    @review = @chair.reviews.find(params[:id])
    if @review.update(review_params)
      redirect_to chair_reviews_path(@chair), notice: "Review successfully updated"
    else  
      render :edit, status: :unprocessable_entity
    end 
  end 

  def destroy
    @review = @chair.reviews.find(params[:id])
    @review.destroy 

    redirect_to chair_reviews_path(@chair), notice: "Review deleted", status: :see_other
  end 
end

private 

def set_chair
  @chair = Chair.find_by!(slug: params[:chair_id])
end


def review_params
  params.require(:review).
   permit(:name, :stars, :comment)
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def get_ratings_percentage(object, rating)
    total_reviews_count = object.reviews.count
    matching_ratings_count = object.reviews.where(stars: rating).count

    return 0 if total_reviews_count.zero? || matching_ratings_count.zero?
    
    ratings_percentage = matching_ratings_count.to_f / total_reviews_count * 100
  end 

  def calculate_width(object, rating)
    "width: #{get_ratings_percentage(object, rating).to_i}%"
  end 

  def reviews_percentage(object, rating)
    "#{get_ratings_percentage(object, rating).to_i}%"
  end 

end

app/views/reviews/_chair_review_data.html.erb
<% 5.downto(1) do |index| %>
  <div class="flex items-center text-sm">
    <dt class="flex flex-1 items-center">
      <p class="w-3 font-medium text-gray-900"><%= index %><span class="sr-only"> star reviews</span></p>
      <div aria-hidden="true" class="ml-1 flex flex-1 items-center">
        <svg class="h-5 w-5 flex-shrink-0 text-yellow-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
        </svg>

        <div class="relative ml-3 flex-1">
          <div class="h-3 rounded-full border border-gray-200 bg-gray-100"></div>
          <div style="<%= calculate_width(@chair, index) %>" class="absolute inset-y-0 rounded-full border border-yellow-400 bg-yellow-400"></div>
        </div>
      </div>
    </dt>
    <dd class="ml-3 w-10 text-right text-sm tabular-nums text-gray-900"><%= reviews_percentage(@chair, index) %></dd>
  </div>
<% end %>

app/views/reviews/_chair_review_stars.html.erb
<!-- Active: "text-yellow-400", Default: "text-gray-300" -->

<% 5.times do |index| %>
  <% if index < review.stars %>
    <svg class="text-yellow-400 h-5 w-5 flex-shrink-0" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
    </svg>
  <% end %>
<% end %>
                  

app/views/reviews/_chair_reviews.html.erb
<div class="mt-16 lg:col-span-7 lg:col-start-6 lg:mt-0">
      <h3 class="sr-only">Recent reviews</h3>

      
      <div class="flow-root">
        <div class="-my-12 divide-y divide-gray-200">
          <% reviews.each do |review| %>
            <div class="py-12">
              <div class="flex items-center">
              
                <img src="https://images.unsplash.com/photo-1502685104226-ee32379fefbe?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=256&h=256&q=80" alt="Emily Selman." class="h-12 w-12 rounded-full">
                <div class="ml-4">
                  <h4 class="text-sm font-bold text-gray-900"><%= link_to review.user.name, user_path(review.user) %></h4>
                  <div class="mt-1 flex items-center">
                    <%= render "reviews/chair_review_stars", review: review %>
                  </div>
                  <p class="sr-only">5 out of 5 stars</p>
                </div>
              </div>

              <div class="mt-4 space-y-6 text-base italic text-gray-600">
                <p><%= review.comment %></p>
                <%= link_to "Edit Review", edit_chair_review_path(review.chair,review.id), class: form_field_button_classes%>
                <%= link_to "Delete Review", chair_review_path(review.chair, review.id), data: { turbo_method: :delete, turbo_confirm: "Really?" }, class: form_field_button_classes %>
              </div>
            </div>
          <% end %>
          
          <!-- More reviews... -->
        </div>
        
      </div>
    </div>

app/views/reviews/_chair_reviews_stars.html.erb
<% 5.times do |index| %>
  <% if index < @chair.average_rating.to_i %>
    <svg class="h-5 w-5 flex-shrink-0 text-yellow-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
    </svg>
  <% else %>
    <svg class="h-5 w-5 flex-shrink-0 text-gray-300" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
   </svg>
  <% end %>
<% end %>

app/views/reviews/_form.html.erb
<div class="container mx-auto px-4 mt-4 max-w-xs py-4">
  <%= simple_form_for [chair, review], defaults: {label_html: {class: label_classes}, input_html: {class: form_input_classes}} do |f| %>

    <% if f.object.errors.present? %>
      <%= render "shared/errors", errors: f.object.errors %>
    <% end %> 

    
    <%= f.input :stars %>
    <%= f.input :comment %>
    <%= f.button :submit, class: form_field_button_classes %>
    
  <% end %>
</div>

app/views/reviews/edit.html.erb
<h1 class="flex justify-center mt-2">Edit review for <%= @chair.company %> <%= @chair.name %></h1>

<%= render "form", chair: @chair, review: @review %>

app/views/reviews/index.html.erb
<div class="flex justify-center rounded-md p-4 mt-4"> 
  Reviews for <%= @chair.company %> <%= @chair.name %>
</div>

<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:grid lg:max-w-7xl lg:grid-cols-12 lg:gap-x-8 lg:px-8 lg:py-32">
    <div class="lg:col-span-4">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">Customer Reviews</h2>

      <div class="mt-3 flex items-center">
        <div>
          <div class="flex items-center">
            <!-- Active: "text-yellow-400", Default: "text-gray-300" -->
            <%= render "chair_reviews_stars" %>           
          </div>
          <p class="sr-only">4 out of 5 stars</p>
        </div>
        <p class="ml-2 text-sm text-gray-900">
          <%= @chair.average_rating.to_i %> stars based on <%= @chair.reviews.size %> reviews
        </p>
      </div>

      <div class="mt-6">
        <h3 class="sr-only">Review data</h3>

        <dl class="space-y-3">
          <%= render "chair_review_data" %>
          
        </dl>
      </div>

      <div class="mt-10">
        <h3 class="text-lg font-medium text-gray-900">Share your thoughts</h3>
        <p class="mt-1 text-sm text-gray-600">If you’ve used this product, share your thoughts with other customers</p>

        <%= link_to "Write a review", new_chair_review_path(@chair), class: "mt-6 inline-flex w-full items-center justify-center rounded-md border border-gray-300 bg-white px-8 py-2 text-sm font-medium text-gray-900 hover:bg-gray-50 sm:w-auto lg:w-full" %>
      </div>
    </div>

    <%= render "chair_reviews", reviews: @reviews %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1 class="flex justify-center mt-2">New review for <%= @chair.company %> <%= @chair.name %></h1>

<%= render "form", chair: @chair, review: @review %>